// ******* AUTOMATICALLY GENERATED BY PyKokkos *******
#ifndef PK_FUNCTOR_INIT_SOL_VIEW_CAST__HPP
#define PK_FUNCTOR_INIT_SOL_VIEW_CAST__HPP

#include <pybind11/pybind11.h>
#include <Kokkos_Core.hpp>
#include <Kokkos_Random.hpp>
#include <Kokkos_Sort.hpp>
#include <fstream>
#include <iostream>
#include <cmath>
#include <functor.hpp>

template <class ExecSpace,class ArgumentMemorySpace> pk_functor_init_sol_view<ExecSpace> pk_functor_init_sol_view_from_pyObject(pybind11::object obj) {Kokkos::View<int32_t*,Kokkos::LayoutLeft,ArgumentMemorySpace,Kokkos::Experimental::DefaultViewHooks> sol_view = getattr(obj,"sol_view").cast<Kokkos::View<int32_t*,Kokkos::LayoutLeft,ArgumentMemorySpace,Kokkos::Experimental::DefaultViewHooks>>();Kokkos::View<int32_t*,Kokkos::LayoutLeft,ArgumentMemorySpace,Kokkos::Experimental::DefaultViewHooks> min_neighbors = getattr(obj,"min_neighbors").cast<Kokkos::View<int32_t*,Kokkos::LayoutLeft,ArgumentMemorySpace,Kokkos::Experimental::DefaultViewHooks>>();ExecSpace pk_exec_space_instance;auto pk_d_sol_view = Kokkos::create_mirror_view_and_copy(pk_exec_space_instance, sol_view);auto pk_d_min_neighbors = Kokkos::create_mirror_view_and_copy(pk_exec_space_instance, min_neighbors);pk_functor_init_sol_view<ExecSpace> pk_f(pk_d_sol_view,pk_d_min_neighbors);return pk_f;}
template <class ExecSpace,class ArgumentMemorySpace> void pk_functor_init_sol_view_to_pyObject(pk_functor_init_sol_view<ExecSpace>& functor, pybind11::object obj) {Kokkos::View<int32_t*,Kokkos::LayoutLeft,ArgumentMemorySpace,Kokkos::Experimental::DefaultViewHooks> sol_view = pybind11::getattr(obj,"sol_view").cast<Kokkos::View<int32_t*,Kokkos::LayoutLeft,ArgumentMemorySpace,Kokkos::Experimental::DefaultViewHooks>>();Kokkos::View<int32_t*,Kokkos::LayoutLeft,ArgumentMemorySpace,Kokkos::Experimental::DefaultViewHooks> min_neighbors = pybind11::getattr(obj,"min_neighbors").cast<Kokkos::View<int32_t*,Kokkos::LayoutLeft,ArgumentMemorySpace,Kokkos::Experimental::DefaultViewHooks>>();Kokkos::resize(sol_view,functor.sol_view.extent(0));Kokkos::deep_copy(sol_view, functor.sol_view);Kokkos::resize(min_neighbors,functor.min_neighbors.extent(0));Kokkos::deep_copy(min_neighbors, functor.min_neighbors);pybind11::setattr(obj,"sol_view",pybind11::cast(sol_view));pybind11::setattr(obj,"min_neighbors",pybind11::cast(min_neighbors));}

#endif