// ******* AUTOMATICALLY GENERATED BY PyKokkos *******
#ifndef PK_FUNCTOR_ROW_MIN_CAST__HPP
#define PK_FUNCTOR_ROW_MIN_CAST__HPP

#include <pybind11/pybind11.h>
#include <Kokkos_Core.hpp>
#include <Kokkos_Random.hpp>
#include <Kokkos_Sort.hpp>
#include <fstream>
#include <iostream>
#include <cmath>
#include <functor.hpp>

template <class ExecSpace,class ArgumentMemorySpace> pk_functor_row_min<ExecSpace> pk_functor_row_min_from_pyObject(pybind11::object obj) {int32_t dim = getattr(obj,"dim").cast<int32_t>();Kokkos::View<int32_t*,Kokkos::LayoutLeft,ArgumentMemorySpace,Kokkos::Experimental::DefaultViewHooks> mins_view = getattr(obj,"mins_view").cast<Kokkos::View<int32_t*,Kokkos::LayoutLeft,ArgumentMemorySpace,Kokkos::Experimental::DefaultViewHooks>>();Kokkos::View<int64_t**,Kokkos::LayoutRight,ArgumentMemorySpace,Kokkos::Experimental::DefaultViewHooks> view2d = getattr(obj,"view2d").cast<Kokkos::View<int64_t**,Kokkos::LayoutRight,ArgumentMemorySpace,Kokkos::Experimental::DefaultViewHooks>>();ExecSpace pk_exec_space_instance;auto pk_d_mins_view = Kokkos::create_mirror_view_and_copy(pk_exec_space_instance, mins_view);auto pk_d_view2d = Kokkos::create_mirror_view_and_copy(pk_exec_space_instance, view2d);pk_functor_row_min<ExecSpace> pk_f(dim,pk_d_mins_view,pk_d_view2d);return pk_f;}
template <class ExecSpace,class ArgumentMemorySpace> void pk_functor_row_min_to_pyObject(pk_functor_row_min<ExecSpace>& functor, pybind11::object obj) {int32_t dim = pybind11::getattr(obj,"dim").cast<int32_t>();Kokkos::View<int32_t*,Kokkos::LayoutLeft,ArgumentMemorySpace,Kokkos::Experimental::DefaultViewHooks> mins_view = pybind11::getattr(obj,"mins_view").cast<Kokkos::View<int32_t*,Kokkos::LayoutLeft,ArgumentMemorySpace,Kokkos::Experimental::DefaultViewHooks>>();Kokkos::View<int64_t**,Kokkos::LayoutRight,ArgumentMemorySpace,Kokkos::Experimental::DefaultViewHooks> view2d = pybind11::getattr(obj,"view2d").cast<Kokkos::View<int64_t**,Kokkos::LayoutRight,ArgumentMemorySpace,Kokkos::Experimental::DefaultViewHooks>>();Kokkos::resize(mins_view,functor.mins_view.extent(0));Kokkos::deep_copy(mins_view, functor.mins_view);pybind11::setattr(obj,"dim",pybind11::cast(dim));pybind11::setattr(obj,"mins_view",pybind11::cast(mins_view));pybind11::setattr(obj,"view2d",pybind11::cast(view2d));}

#endif